name: accent_cli_dart
description: A Dart implementation of accent-cli for managing translations with Accent
version: 0.1.6
homepage: https://github.com/moaazsalama/accent-cli-dart
repository: https://github.com/moaazsalama/accent-cli-dart
issue_tracker: https://github.com/moaazsalama/accent-cli-dart/issues

environment:
  sdk: '>=2.12.0 <4.0.0'

executables:
  accent: main


dependencies:
  args: ^2.3.0
  http: ^1.2.2
  dio: ^5.8.0+1
  yaml: ^3.1.0
  path: ^1.8.0
  glob: ^2.0.2
  colorize: ^3.0.0
  cli_util: ^0.3.5
  io: ^1.0.3
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

assets:
  - accent.json
  - assets/translations/

